/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.vop.augumented;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int augmentedView=0x7f05000c;
        public static final int berichten=0x7f050005;
        public static final int email_tekst=0x7f05001c;
        public static final int go_knop=0x7f05001e;
        public static final int group1=0x7f050010;
        public static final int hoofdscherm=0x7f05000e;
        public static final int info=0x7f05000d;
        public static final int invul_box=0x7f05001d;
        public static final int kaart=0x7f05000f;
        public static final int km_1=0x7f050012;
        public static final int km_10=0x7f050014;
        public static final int km_20=0x7f050015;
        public static final int km_5=0x7f050013;
        public static final int locaties=0x7f050007;
        public static final int m_500=0x7f050011;
        public static final int myLocationText=0x7f050016;
        public static final int myMapView=0x7f050017;
        public static final int optie_1=0x7f050002;
        public static final int optie_2=0x7f050003;
        public static final int preview=0x7f05000b;
        public static final int profiel=0x7f050009;
        public static final int refresh=0x7f050020;
        public static final int tableLayout1=0x7f050004;
        public static final int textView1=0x7f050018;
        public static final int textView2=0x7f050019;
        public static final int textView3=0x7f05001a;
        public static final int textView4=0x7f05001b;
        public static final int traject_update=0x7f05001f;
        public static final int trajecten=0x7f050006;
        public static final int uitloggen=0x7f05000a;
        public static final int vrienden=0x7f050008;
        public static final int widget32=0x7f050000;
        public static final int widget55=0x7f050001;
    }
    public static final class layout {
        public static final int berichten_layout=0x7f030000;
        public static final int berichten_menu=0x7f030001;
        public static final int hoofdmenu_layout=0x7f030002;
        public static final int hoofdmenu_menu=0x7f030003;
        public static final int locaties_layout=0x7f030004;
        public static final int locaties_map_menu=0x7f030005;
        public static final int locaties_menu=0x7f030006;
        public static final int locatiesmap_layout=0x7f030007;
        public static final int profiel_layout=0x7f030008;
        public static final int profiel_menu=0x7f030009;
        public static final int startupactivity_layout=0x7f03000a;
        public static final int trajecten_layout=0x7f03000b;
        public static final int trajecten_menu=0x7f03000c;
        public static final int vrienden_layout=0x7f03000d;
        public static final int vrienden_menu=0x7f03000e;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
